"""add AI fields to applications

Revision ID: 847f6856d847
Revises: 0cc2e5fea8d1
Create Date: 2026-05-26 10:58:59.989218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '847f6856d847'
down_revision: Union[str, Sequence[str], None] = '0cc2e5fea8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('job_description', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('extracted_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('applications', sa.Column('generated_cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'generated_cover_letter')
    op.drop_column('applications', 'extracted_requirements')
    op.drop_column('applications', 'job_description')
    # ### end Alembic commands ###
